# Base Jekyll configuration

# Grunt handles some Jekyll configuration. If you set something here and
# it doesn't work, check if it is set in the Gruntfile.

# Use _config.build.yml to override these settings on `grunt build`.

name: sketchbook
description: nclud's sketchbook
url: http://sketchbook.nclud.com

authors:
  default:
    name: "nclud"
    image: /img/nclud-logo.png
    twitter: nclud
    bio: "A creative design agency focused on unique, stylish and usable experiences across a multitude of verticals, mediums and devices. We work with early stage start-ups, to the Fortune 100, and everyone in between."
  jesse:
    name: "Jesse Shawl"
    image: https://0.gravatar.com/avatar/495991dab64918eb18680073115163aa?d=https%3A%2F%2Fidenticons.github.com%2F0837445cdfc525ca7dcf22cc5b2f8747.png&r=x&s=440
    twitter: jshawl
    bio: "Jesse Shawl is a Front End Developer at nclud - whose focus intersects web performance and cutting edge browser interactivity. He's an open source advocate who enjoys building tools for the web with third party API's and mesmerizing CSS animations."
  jared:
    name: "Jared Laser"
    image: foo.jpg
    twitter: imjared
    bio: "This is Jared's Bio"
  max:
    name: "Maxim Leyzerovich"
    image: bar.jpg
    twitter: duqe
    bio: "this is maxs bio"

# Exclude directories and/or files from the conversion.
# Grunt moves image files and asset directories.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

# Force inclusion of directories and/or files in the conversion.
# .htaccess is a good example since dotfiles are excluded by default.
include: ['.htaccess']

# Default post path style
permalink: /:title/

# Publish posts with future date.
# _config.build.yml sets this to false on `grunt build`
future: true

# Compile posts in the _drafts directory.
# _config.build.yml sets this to false on `grunt build`
show_drafts: true

# Split posts over multiple subdirectories called “page2”, “page3”, … “pageN”
paginate: 5
paginate_path: 'page:num'

# Markdown library
markdown: maruku

# Use Pygments to highlight code blocks
pygments: true
